### PR TITLE
Fix flakey tests in securenaming

### LINKED ISSUE #28: Investigate test flakeness
Currently `TestGetPodServices` fails occasionally. We should investigate and fix this flakiness.

### PR DESCRIPTION
**Pull request by lookuptable**
This closes #28 .

### CODE REVIEW

File: controller/securenaming_test.go [hunk 1]
```diff
@@ -195,8 +197,12 @@ func TestGetPodServices(t *testing.T) {
 		}
 
 		actualServices := snc.getPodServices(testCase.pod)
+		sort.Sort(sortableServices(actualServices))
 
-		if !reflect.DeepEqual(actualServices, testCase.expectedServices) {
+		expectedServices := testCase.expectedServices
+		sort.Sort(sortableServices(expectedServices))
```
Comment (lizan) [inline controller/securenaming_test.go]: I believe expectedServices is already sorted, so no need Sort again?

Comment (lookuptable) [inline controller/securenaming_test.go]: Good point. Done.
