### PR TITLE
Fix test flakyness in generate_cert_test.go

### LINKED ISSUE #253: Flaky test in generate_cert
This is flaky, and seems to be related to the cert timestamp.

W0831 04:01:56.424] PASS: //pkg/pki:go_default_test
W0831 04:01:56.546] ____[473 / 789] Testing //pkg/pki/ca:go_default_test
W0831 04:01:56.932] FAIL: //pkg/pki/ca:go_default_test (see /home/bootstrap/.cache/bazel/_bazel_bootstrap/82c87f91d10397dd2101a6893e4c013b/execroot/__main__/bazel-out/local-fastbuild/testlogs/pkg/pki/ca/go_default_test/test.log)
W0831 04:01:56.932] ____From Testing //pkg/pki/ca:go_default_test:
I0831 04:01:57.032] ==================== Test output for //pkg/pki/ca:go_default_test:
I0831 04:01:57.033] E0831 04:01:56.865231       9 generate_cert.go:82] RSA key generation failed with error crypto/rsa: too few primes of given length to generate an RSA key.
I0831 04:01:57.033] --- FAIL: TestGenCert (0.04s)
I0831 04:01:57.033] 	generate_cert_test.go:82: now: 2017-08-31 04:01:57 +0000 UTC
I0831 04:01:57.033] 	generate_cert_test.go:109: failed to verify certificate: x509: certificate has expired or is not yet valid
I0831 04:01:57.034] 	generate_cert_test.go:277: failed to verify certificate: x509: certificate has expired or is not yet valid
I0831 04:01:57.034] 	generate_cert_test.go:277: failed to verify certificate: x509: certificate has expired or is not yet valid
I0831 04:01:57.034] 	generate_cert_test.go:277: failed to verify certificate: x509: certificate has expired or is not yet valid
I0831 04:01:57.034] 	generate_cert_test.go:277: failed to verify certificate: x509: certificate has expired or is not yet valid
I0831 04:01:57.034] 	generate_cert_test.go:277: failed to verify certificate: x509: certificate has expired or is not yet valid
I0831 04:01:57.035] 	generate_cert_test.go:277: failed to verify certificate: x509: certificate has expired or is not yet valid
I0831 04:01:57.035] FAIL
I0831 04:01:57.035] Use --strategy=TestRunner=standalone to disable sandboxing for the failing actions.

### PR DESCRIPTION
**Pull request by lookuptable**
The flakyness was due to we set the NotBefore field to current time.
However when verifying the cert, the NotBefore field is required to be
strictly earlier than the time at which verification happens. Thus
test fails occasionally if there isn't sufficient time elapsed between
cert issuance and cert verification.

Fixes #253

**Release note**:

```NONE
```

/assign @wattli

### CODE REVIEW

File: pkg/pki/ca/generate_cert_test.go [hunk 1]
```diff
@@ -76,7 +76,9 @@ func TestGenCSRWithInvalidOption(t *testing.T) {
 }
 
 func TestGenCert(t *testing.T) {
-	caCertNotBefore := now
+	// set "notBefore" to be 5 minutes aga, this ensures the issued certifiate to
```
Comment (wattli) [inline pkg/pki/ca/generate_cert_test.go]: s/aga/ago
